language: java

matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk8
    - os: linux
      sudo: false
      jdk: openjdk8
    - os: linux
      sudo: false
      jdk: oraclejdk9 # JDK 9+175 or newer

script: ./gradlew :provider:check --info --stacktrace --console=plain --max-workers=1 --no-daemon -Dkotlin.compiler.execution.strategy=in-proces -Dkotlin.colors.enabled=false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
