name: add-to-dev-prod-project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

jobs:
  add-to-dev-prod-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check label
        if: (github.event.issue!=null && contains(github.event.issue.labels.*.name, '@dev-productivity')) || (github.event.pull_request!=null && contains(github.event.pull_request.labels.*.name, '@dev-productivity'))
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GRADLE_GH_ORG_BOARD_ACCESS_TOKEN }}
        run: curl -s https://raw.githubusercontent.com/gradle/gradle/master/.github/workflows/add-to-github-project.sh | bash -s 17 ${{ github.event.pull_request.node_id }}
